### ISSUE TITLE
Rich Text Default Field disappears, input loses app focus

### ISSUE THREAD

**Issue by NickDeckerDevs** [jazzyclimber/hs-desktop-app#1]
steps to reproduce.
Add rich text field
Mouse into NAME or LABEL fields and press a key.

DEFAULT field disappears
Cursor also loses app focus, can no longer type in input field.

Tested on mac m1 max in 
v1 hubspot co-pilot 
v2 hs-desktop-app
Same issue, video of behavior below
v1: https://share.getcloudapp.com/d5unzGO2
v2: https://share.getcloudapp.com/v1uQAdLl

**Comment by jazzyclimber** [comment]
Not sure what commit fixed this but its fixed now...

**Comment by jazzyclimber** [comment]
https://github.com/jazzyclimber/hs-desktop-app/commit/42d30b887267f30fa31f0869be10d34fab2de074
