### ISSUE TITLE
Files Not Saving

### ISSUE THREAD

**Issue by WeAreELIC** [jazzyclimber/hs-desktop-app#6]
Hey, I'm on a Mac running macOS Big Sur – version 11.6.4 (20G417). I'm using VS Code as my text editor.

Clicking the save button does not actually change the file but the changes are saved in Copilot, even if I close Copilot, set the theme directory, and edit the same file—I see my changes but it's not changing the actual file (looking at it in VS Code and Finder). Thoughts?

**Comment by WeAreELIC** [comment]
Never mind: I set my Theme Directory to the root of my project, which contains a `src` and `dist` folder. Copilot is loading the fields.json files from both of the folders and I was editing the wrong one.

**Comment by jazzyclimber** [comment]
Got it -- yea I recommend setting the theme directory to the root theme directory.
